app:
  mqtt:
    client-id: rpc-server
    host: localhost
    port: 8883
    register-request-topic: "/register-request"
    register-response-topic: "/register-response"
    heartbeat-topic: "/heartbeat"
    invoke-request-topic: "/invoke-request"
    invoke-response-topic: "/invoke-response"

logging:
  level:
    io.rapidw.mqttrpc: debug

spring:
  datasource:
    url: jdbc:mysql://10.11.2.29:3306/rpc?characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: sdt@2022
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true